### ISSUE TITLE
Milestone 1: Create a minimally playable game

### ISSUE THREAD

**Issue by kuosandys** [TheChopsticks/music-app#16]
For our first milestone, we would like to create a minimally playable version of our music game with the following requirements.

As a user:
- [x] I am presented with a welcome screen when I navigate to the app's webpage
- [x] I can read the game's instructions
- [x] For each question:
  - [x] I can hear two tones played
  - [x] I can replay the tones as many times as I want
  - [x] I can guess the interval between the tones
  - [x] I can change my answer as many times as I want before submission
  - [x] I can skip the question
- [x] I can see my current score
- [x] I can see the current question number I'm on
- [x] At the end of the game, I can see how many questions I've answered correctly
- [x] I can replay the game

In addition, our app should be deployed, and it should look somewhat nice 🙂

**Comment by kuosandys** [comment]
DONE 🎉
